import { PrismaClient, UserRole, Gender } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export async function seedUsers() {
  console.log('🌱 Seeding Users...');

  const hashedPassword = await bcrypt.hash('SuperAdmin@123', 10);
  const doctorPassword = await bcrypt.hash('Doctor@123', 10);
  const staffPassword = await bcrypt.hash('Staff@123', 10);
  const patientPassword = await bcrypt.hash('Patient@123', 10);

  const users = [
    // Super Admin
    {
      id: 'user-superadmin-001',
      email: 'superadmin@hospital.com',
      username: 'superadmin',
      password: hashedPassword,
      role: UserRole.SUPER_ADMIN,
      firstName: 'System',
      lastName: 'Administrator',
      phone: '+1-555-0100',
      gender: Gender.MALE,
      dateOfBirth: new Date('1980-01-01'),
      address: '123 Admin Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10001',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Admin
    {
      id: 'user-admin-001',
      email: 'admin@hospital.com',
      username: 'admin',
      password: hashedPassword,
      role: UserRole.ADMIN,
      firstName: 'Admin',
      lastName: 'User',
      phone: '+1-555-0101',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1985-05-15'),
      address: '456 Management Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10002',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Doctors
    {
      id: 'user-doctor-001',
      email: 'sarah.johnson@hospital.com',
      username: 'dr.sarah',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'Sarah',
      lastName: 'Johnson',
      phone: '+1-555-1001',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1982-03-20'),
      address: '789 Medical Plaza',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10003',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-doctor-002',
      email: 'michael.chen@hospital.com',
      username: 'dr.michael',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'Michael',
      lastName: 'Chen',
      phone: '+1-555-1002',
      gender: Gender.MALE,
      dateOfBirth: new Date('1978-07-12'),
      address: '234 Healthcare Blvd',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10004',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-doctor-003',
      email: 'emily.brown@hospital.com',
      username: 'dr.emily',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'Emily',
      lastName: 'Brown',
      phone: '+1-555-1003',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1985-11-30'),
      address: '567 Clinic Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10005',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-doctor-004',
      email: 'david.wilson@hospital.com',
      username: 'dr.david',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'David',
      lastName: 'Wilson',
      phone: '+1-555-1004',
      gender: Gender.MALE,
      dateOfBirth: new Date('1980-02-14'),
      address: '890 Doctor Lane',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10006',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-doctor-005',
      email: 'jessica.martinez@hospital.com',
      username: 'dr.jessica',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'Jessica',
      lastName: 'Martinez',
      phone: '+1-555-1005',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1987-09-22'),
      address: '123 Pediatric Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10007',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-doctor-006',
      email: 'robert.taylor@hospital.com',
      username: 'dr.robert',
      password: doctorPassword,
      role: UserRole.DOCTOR,
      firstName: 'Robert',
      lastName: 'Taylor',
      phone: '+1-555-1006',
      gender: Gender.MALE,
      dateOfBirth: new Date('1979-06-18'),
      address: '456 Neuro Center',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10008',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Nurses
    {
      id: 'user-nurse-001',
      email: 'mary.williams@hospital.com',
      username: 'nurse.mary',
      password: staffPassword,
      role: UserRole.NURSE,
      firstName: 'Mary',
      lastName: 'Williams',
      phone: '+1-555-2001',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1990-04-10'),
      address: '789 Nursing Plaza',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10009',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-nurse-002',
      email: 'jennifer.davis@hospital.com',
      username: 'nurse.jennifer',
      password: staffPassword,
      role: UserRole.NURSE,
      firstName: 'Jennifer',
      lastName: 'Davis',
      phone: '+1-555-2002',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1988-08-25'),
      address: '234 Care Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10010',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Receptionists
    {
      id: 'user-receptionist-001',
      email: 'lisa.thompson@hospital.com',
      username: 'reception.lisa',
      password: staffPassword,
      role: UserRole.RECEPTIONIST,
      firstName: 'Lisa',
      lastName: 'Thompson',
      phone: '+1-555-3001',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1992-12-05'),
      address: '567 Front Desk Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10011',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-receptionist-002',
      email: 'karen.moore@hospital.com',
      username: 'reception.karen',
      password: staffPassword,
      role: UserRole.RECEPTIONIST,
      firstName: 'Karen',
      lastName: 'Moore',
      phone: '+1-555-3002',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1994-03-15'),
      address: '890 Reception Blvd',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10012',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Pharmacists
    {
      id: 'user-pharmacist-001',
      email: 'john.pharmacist@hospital.com',
      username: 'pharma.john',
      password: staffPassword,
      role: UserRole.PHARMACIST,
      firstName: 'John',
      lastName: 'Anderson',
      phone: '+1-555-4001',
      gender: Gender.MALE,
      dateOfBirth: new Date('1986-07-20'),
      address: '123 Pharmacy Lane',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10013',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-pharmacist-002',
      email: 'patricia.white@hospital.com',
      username: 'pharma.patricia',
      password: staffPassword,
      role: UserRole.PHARMACIST,
      firstName: 'Patricia',
      lastName: 'White',
      phone: '+1-555-4002',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1989-10-08'),
      address: '456 Medicine Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10014',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Lab Technicians
    {
      id: 'user-lab-001',
      email: 'thomas.lab@hospital.com',
      username: 'lab.thomas',
      password: staffPassword,
      role: UserRole.LAB_TECHNICIAN,
      firstName: 'Thomas',
      lastName: 'Garcia',
      phone: '+1-555-5001',
      gender: Gender.MALE,
      dateOfBirth: new Date('1991-05-12'),
      address: '789 Laboratory Blvd',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10015',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-lab-002',
      email: 'nancy.rodriguez@hospital.com',
      username: 'lab.nancy',
      password: staffPassword,
      role: UserRole.LAB_TECHNICIAN,
      firstName: 'Nancy',
      lastName: 'Rodriguez',
      phone: '+1-555-5002',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1993-09-30'),
      address: '234 Testing Center',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10016',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Radiologist
    {
      id: 'user-radiologist-001',
      email: 'daniel.martin@hospital.com',
      username: 'radio.daniel',
      password: doctorPassword,
      role: UserRole.RADIOLOGIST,
      firstName: 'Daniel',
      lastName: 'Martin',
      phone: '+1-555-6001',
      gender: Gender.MALE,
      dateOfBirth: new Date('1984-11-22'),
      address: '567 Imaging Center',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10017',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Accountant
    {
      id: 'user-accountant-001',
      email: 'richard.accountant@hospital.com',
      username: 'account.richard',
      password: staffPassword,
      role: UserRole.ACCOUNTANT,
      firstName: 'Richard',
      lastName: 'Jackson',
      phone: '+1-555-7001',
      gender: Gender.MALE,
      dateOfBirth: new Date('1983-02-28'),
      address: '890 Finance Plaza',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10018',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },

    // Patients
    {
      id: 'user-patient-001',
      email: 'john.doe@email.com',
      username: 'john.doe',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'John',
      lastName: 'Doe',
      phone: '+1-555-8001',
      gender: Gender.MALE,
      dateOfBirth: new Date('1990-06-15'),
      address: '123 Patient Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10019',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-002',
      email: 'jane.smith@email.com',
      username: 'jane.smith',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Jane',
      lastName: 'Smith',
      phone: '+1-555-8002',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1988-09-20'),
      address: '456 Resident Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10020',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-003',
      email: 'robert.brown@email.com',
      username: 'robert.brown',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Robert',
      lastName: 'Brown',
      phone: '+1-555-8003',
      gender: Gender.MALE,
      dateOfBirth: new Date('1975-03-10'),
      address: '789 Community Blvd',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10021',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-004',
      email: 'susan.wilson@email.com',
      username: 'susan.wilson',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Susan',
      lastName: 'Wilson',
      phone: '+1-555-8004',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1995-12-25'),
      address: '234 Neighborhood St',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10022',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-005',
      email: 'william.jones@email.com',
      username: 'william.jones',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'William',
      lastName: 'Jones',
      phone: '+1-555-8005',
      gender: Gender.MALE,
      dateOfBirth: new Date('1982-07-30'),
      address: '567 Town Square',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10023',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-006',
      email: 'patricia.miller@email.com',
      username: 'patricia.miller',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Patricia',
      lastName: 'Miller',
      phone: '+1-555-8006',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1992-04-18'),
      address: '890 City Center',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10024',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-007',
      email: 'charles.davis@email.com',
      username: 'charles.davis',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Charles',
      lastName: 'Davis',
      phone: '+1-555-8007',
      gender: Gender.MALE,
      dateOfBirth: new Date('1968-11-05'),
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10025',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-008',
      email: 'linda.martinez@email.com',
      username: 'linda.martinez',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Linda',
      lastName: 'Martinez',
      phone: '+1-555-8008',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('1985-02-14'),
      address: '456 Oak Avenue',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10026',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-009',
      email: 'james.garcia@email.com',
      username: 'james.garcia',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'James',
      lastName: 'Garcia',
      phone: '+1-555-8009',
      gender: Gender.MALE,
      dateOfBirth: new Date('1978-08-22'),
      address: '789 Elm Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10027',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
    {
      id: 'user-patient-010',
      email: 'barbara.rodriguez@email.com',
      username: 'barbara.rodriguez',
      password: patientPassword,
      role: UserRole.PATIENT,
      firstName: 'Barbara',
      lastName: 'Rodriguez',
      phone: '+1-555-8010',
      gender: Gender.FEMALE,
      dateOfBirth: new Date('2000-05-30'),
      address: '234 Pine Road',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      pincode: '10028',
      isActive: true,
      isEmailVerified: true,
      emailVerifiedAt: new Date(),
    },
  ];

  for (const userData of users) {
    await prisma.user.upsert({
      where: { email: userData.email },
      update: {},
      create: userData,
    });
  }

  console.log(`✅ Seeded ${users.length} users`);
}
