import { PrismaClient, BloodGroup } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedPatients() {
  console.log('🌱 Seeding Patients...');

  const patients = [
    {
      id: 'patient-001',
      userId: 'user-patient-001',
      patientId: 'PAT001',
      bloodGroup: BloodGroup.O_POSITIVE,
      height: 175,
      weight: 70,
      bmi: 22.9,
      emergencyContactName: 'Mary Doe',
      emergencyContactPhone: '+1-555-8101',
      emergencyContactRelation: 'Spouse',
      insuranceProvider: 'Blue Cross',
      insurancePolicyNumber: 'BC123456789',
      insuranceValidTill: new Date('2027-12-31'),
      allergies: 'Penicillin',
      chronicConditions: 'Hypertension',
      currentMedications: 'Lisinopril 10mg daily',
      isActive: true,
      registrationDate: new Date('2024-01-15'),
    },
    {
      id: 'patient-002',
      userId: 'user-patient-002',
      patientId: 'PAT002',
      bloodGroup: BloodGroup.A_POSITIVE,
      height: 165,
      weight: 60,
      bmi: 22.0,
      emergencyContactName: 'Tom Smith',
      emergencyContactPhone: '+1-555-8102',
      emergencyContactRelation: 'Husband',
      insuranceProvider: 'Aetna',
      insurancePolicyNumber: 'AE987654321',
      insuranceValidTill: new Date('2026-06-30'),
      allergies: 'Shellfish, Latex',
      chronicConditions: 'Asthma',
      currentMedications: 'Albuterol inhaler as needed',
      isActive: true,
      registrationDate: new Date('2024-02-10'),
    },
    {
      id: 'patient-003',
      userId: 'user-patient-003',
      patientId: 'PAT003',
      bloodGroup: BloodGroup.B_POSITIVE,
      height: 180,
      weight: 85,
      bmi: 26.2,
      emergencyContactName: 'Sarah Brown',
      emergencyContactPhone: '+1-555-8103',
      emergencyContactRelation: 'Daughter',
      insuranceProvider: 'UnitedHealth',
      insurancePolicyNumber: 'UH456789123',
      insuranceValidTill: new Date('2027-03-31'),
      allergies: 'None',
      chronicConditions: 'Type 2 Diabetes',
      currentMedications: 'Metformin 500mg twice daily',
      isActive: true,
      registrationDate: new Date('2023-11-20'),
    },
    {
      id: 'patient-004',
      userId: 'user-patient-004',
      patientId: 'PAT004',
      bloodGroup: BloodGroup.AB_POSITIVE,
      height: 160,
      weight: 55,
      bmi: 21.5,
      emergencyContactName: 'Mark Wilson',
      emergencyContactPhone: '+1-555-8104',
      emergencyContactRelation: 'Father',
      insuranceProvider: 'Cigna',
      insurancePolicyNumber: 'CG789123456',
      insuranceValidTill: new Date('2026-12-31'),
      allergies: 'Dust, Pollen',
      chronicConditions: 'None',
      currentMedications: 'None',
      isActive: true,
      registrationDate: new Date('2024-03-05'),
    },
    {
      id: 'patient-005',
      userId: 'user-patient-005',
      patientId: 'PAT005',
      bloodGroup: BloodGroup.O_NEGATIVE,
      height: 178,
      weight: 82,
      bmi: 25.9,
      emergencyContactName: 'Emma Jones',
      emergencyContactPhone: '+1-555-8105',
      emergencyContactRelation: 'Wife',
      insuranceProvider: 'Humana',
      insurancePolicyNumber: 'HU321654987',
      insuranceValidTill: new Date('2027-09-30'),
      allergies: 'Aspirin',
      chronicConditions: 'High Cholesterol',
      currentMedications: 'Atorvastatin 20mg daily',
      isActive: true,
      registrationDate: new Date('2023-08-12'),
    },
    {
      id: 'patient-006',
      userId: 'user-patient-006',
      patientId: 'PAT006',
      bloodGroup: BloodGroup.A_NEGATIVE,
      height: 168,
      weight: 65,
      bmi: 23.0,
      emergencyContactName: 'David Miller',
      emergencyContactPhone: '+1-555-8106',
      emergencyContactRelation: 'Brother',
      insuranceProvider: 'Kaiser',
      insurancePolicyNumber: 'KP654987321',
      insuranceValidTill: new Date('2026-08-31'),
      allergies: 'Codeine',
      chronicConditions: 'Migraine',
      currentMedications: 'Sumatriptan 50mg as needed',
      isActive: true,
      registrationDate: new Date('2024-04-18'),
    },
    {
      id: 'patient-007',
      userId: 'user-patient-007',
      patientId: 'PAT007',
      bloodGroup: BloodGroup.B_NEGATIVE,
      height: 172,
      weight: 78,
      bmi: 26.4,
      emergencyContactName: 'Margaret Davis',
      emergencyContactPhone: '+1-555-8107',
      emergencyContactRelation: 'Wife',
      insuranceProvider: 'Medicare',
      insurancePolicyNumber: 'MC147258369',
      insuranceValidTill: new Date('2030-12-31'),
      allergies: 'Sulfa drugs',
      chronicConditions: 'Coronary Artery Disease, Hypertension',
      currentMedications: 'Aspirin 81mg, Metoprolol 50mg, Lisinopril 20mg',
      isActive: true,
      registrationDate: new Date('2023-05-10'),
    },
    {
      id: 'patient-008',
      userId: 'user-patient-008',
      patientId: 'PAT008',
      bloodGroup: BloodGroup.O_POSITIVE,
      height: 163,
      weight: 58,
      bmi: 21.8,
      emergencyContactName: 'Carlos Martinez',
      emergencyContactPhone: '+1-555-8108',
      emergencyContactRelation: 'Husband',
      insuranceProvider: 'Blue Shield',
      insurancePolicyNumber: 'BS963852741',
      insuranceValidTill: new Date('2027-04-30'),
      allergies: 'None',
      chronicConditions: 'Hypothyroidism',
      currentMedications: 'Levothyroxine 75mcg daily',
      isActive: true,
      registrationDate: new Date('2024-01-22'),
    },
    {
      id: 'patient-009',
      userId: 'user-patient-009',
      patientId: 'PAT009',
      bloodGroup: BloodGroup.A_POSITIVE,
      height: 176,
      weight: 90,
      bmi: 29.1,
      emergencyContactName: 'Maria Garcia',
      emergencyContactPhone: '+1-555-8109',
      emergencyContactRelation: 'Wife',
      insuranceProvider: 'Anthem',
      insurancePolicyNumber: 'AN852963741',
      insuranceValidTill: new Date('2026-11-30'),
      allergies: 'Iodine contrast',
      chronicConditions: 'Obesity, Sleep Apnea',
      currentMedications: 'CPAP therapy at night',
      isActive: true,
      registrationDate: new Date('2023-09-15'),
    },
    {
      id: 'patient-010',
      userId: 'user-patient-010',
      patientId: 'PAT010',
      bloodGroup: BloodGroup.AB_NEGATIVE,
      height: 158,
      weight: 52,
      bmi: 20.8,
      emergencyContactName: 'Jose Rodriguez',
      emergencyContactPhone: '+1-555-8110',
      emergencyContactRelation: 'Father',
      insuranceProvider: 'Medicaid',
      insurancePolicyNumber: 'MD741852963',
      insuranceValidTill: new Date('2026-12-31'),
      allergies: 'None',
      chronicConditions: 'None',
      currentMedications: 'None',
      isActive: true,
      registrationDate: new Date('2024-05-08'),
    },
  ];

  for (const patientData of patients) {
    await prisma.patient.upsert({
      where: { patientId: patientData.patientId },
      update: {},
      create: patientData,
    });
  }

  console.log(`✅ Seeded ${patients.length} patients`);
}
