import { PrismaClient, MedicationForm } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedMedications() {
  console.log('🌱 Seeding Medications...');

  const medications = [
    // Cardiovascular
    {
      id: 'med-001',
      name: 'Lisinopril',
      genericName: 'Lisinopril',
      brandName: 'Prinivil, Zestril',
      manufacturer: 'Various',
      medicationForm: MedicationForm.TABLET,
      strength: '10mg',
      category: 'Cardiovascular',
      drugClass: 'ACE Inhibitor',
      commonUses: 'Treatment of hypertension, heart failure, post-myocardial infarction',
      sideEffects: 'Dry cough, dizziness, headache, fatigue',
      contraindications: 'Pregnancy, bilateral renal artery stenosis, history of angioedema',
      warnings: 'Monitor kidney function and potassium levels regularly',
      unitPrice: 0.50,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-002',
      name: 'Atorvastatin',
      genericName: 'Atorvastatin Calcium',
      brandName: 'Lipitor',
      manufacturer: 'Pfizer',
      medicationForm: MedicationForm.TABLET,
      strength: '20mg',
      category: 'Cardiovascular',
      drugClass: 'Statin',
      commonUses: 'Treatment of high cholesterol, prevention of cardiovascular disease',
      sideEffects: 'Muscle pain, liver enzyme elevation, digestive problems',
      contraindications: 'Active liver disease, pregnancy, breastfeeding',
      warnings: 'Monitor liver function. Report unexplained muscle pain immediately',
      unitPrice: 1.20,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-003',
      name: 'Metoprolol',
      genericName: 'Metoprolol Tartrate',
      brandName: 'Lopressor',
      manufacturer: 'Novartis',
      medicationForm: MedicationForm.TABLET,
      strength: '50mg',
      category: 'Cardiovascular',
      drugClass: 'Beta Blocker',
      commonUses: 'Treatment of hypertension, angina, heart failure, arrhythmias',
      sideEffects: 'Fatigue, dizziness, slow heart rate, cold extremities',
      contraindications: 'Severe bradycardia, heart block, cardiogenic shock',
      warnings: 'Do not stop abruptly. May mask signs of hypoglycemia in diabetics',
      unitPrice: 0.80,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-004',
      name: 'Aspirin',
      genericName: 'Acetylsalicylic Acid',
      brandName: 'Bayer Aspirin',
      manufacturer: 'Bayer',
      medicationForm: MedicationForm.TABLET,
      strength: '81mg',
      category: 'Cardiovascular',
      drugClass: 'Antiplatelet Agent',
      commonUses: 'Prevention of heart attack and stroke, pain relief, fever reduction',
      sideEffects: 'Stomach upset, increased bleeding risk, heartburn',
      contraindications: 'Active bleeding, hemophilia, aspirin allergy',
      warnings: 'May increase bleeding risk. Avoid in children with viral infections',
      unitPrice: 0.10,
      isAvailable: true,
      requiresPrescription: false,
    },

    // Diabetes
    {
      id: 'med-005',
      name: 'Metformin',
      genericName: 'Metformin Hydrochloride',
      brandName: 'Glucophage',
      manufacturer: 'Bristol-Myers Squibb',
      medicationForm: MedicationForm.TABLET,
      strength: '500mg',
      category: 'Antidiabetic',
      drugClass: 'Biguanide',
      commonUses: 'Treatment of Type 2 Diabetes Mellitus',
      sideEffects: 'Nausea, diarrhea, stomach upset, metallic taste',
      contraindications: 'Severe kidney disease, metabolic acidosis, diabetic ketoacidosis',
      warnings: 'Take with meals. Hold before contrast imaging studies',
      unitPrice: 0.30,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-006',
      name: 'Insulin Glargine',
      genericName: 'Insulin Glargine',
      brandName: 'Lantus',
      manufacturer: 'Sanofi',
      medicationForm: MedicationForm.INJECTION,
      strength: '100 units/mL',
      category: 'Antidiabetic',
      drugClass: 'Long-acting Insulin',
      commonUses: 'Blood glucose control in diabetes mellitus',
      sideEffects: 'Hypoglycemia, weight gain, injection site reactions',
      contraindications: 'Hypoglycemia',
      warnings: 'Monitor blood glucose regularly. Adjust dose as needed',
      unitPrice: 25.00,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Respiratory
    {
      id: 'med-007',
      name: 'Albuterol',
      genericName: 'Albuterol Sulfate',
      brandName: 'Ventolin, Proventil',
      manufacturer: 'GlaxoSmithKline',
      medicationForm: MedicationForm.INHALER,
      strength: '90mcg/actuation',
      category: 'Respiratory',
      drugClass: 'Beta-2 Agonist',
      commonUses: 'Relief of bronchospasm in asthma and COPD',
      sideEffects: 'Tremor, nervousness, rapid heartbeat, headache',
      contraindications: 'Hypersensitivity to albuterol',
      warnings: 'Seek medical attention if more than usual doses are needed',
      unitPrice: 15.00,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-008',
      name: 'Montelukast',
      genericName: 'Montelukast Sodium',
      brandName: 'Singulair',
      manufacturer: 'Merck',
      medicationForm: MedicationForm.TABLET,
      strength: '10mg',
      category: 'Respiratory',
      drugClass: 'Leukotriene Receptor Antagonist',
      commonUses: 'Prevention of asthma symptoms and allergic rhinitis',
      sideEffects: 'Headache, stomach pain, mood changes',
      contraindications: 'Hypersensitivity to montelukast',
      warnings: 'Not for acute asthma attacks. Monitor for mood changes',
      unitPrice: 2.50,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Antibiotics
    {
      id: 'med-009',
      name: 'Amoxicillin',
      genericName: 'Amoxicillin Trihydrate',
      brandName: 'Amoxil',
      manufacturer: 'GlaxoSmithKline',
      medicationForm: MedicationForm.CAPSULE,
      strength: '500mg',
      category: 'Antibiotic',
      drugClass: 'Penicillin',
      commonUses: 'Treatment of bacterial infections',
      sideEffects: 'Diarrhea, nausea, rash, yeast infection',
      contraindications: 'Penicillin allergy',
      warnings: 'Complete full course even if feeling better',
      unitPrice: 0.60,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-010',
      name: 'Azithromycin',
      genericName: 'Azithromycin Dihydrate',
      brandName: 'Zithromax',
      manufacturer: 'Pfizer',
      medicationForm: MedicationForm.TABLET,
      strength: '250mg',
      category: 'Antibiotic',
      drugClass: 'Macrolide',
      commonUses: 'Treatment of respiratory, skin, and other bacterial infections',
      sideEffects: 'Diarrhea, nausea, abdominal pain',
      contraindications: 'Liver disease, myasthenia gravis, QT prolongation',
      warnings: 'May cause abnormal heart rhythms. Take on empty stomach',
      unitPrice: 3.50,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-011',
      name: 'Ciprofloxacin',
      genericName: 'Ciprofloxacin Hydrochloride',
      brandName: 'Cipro',
      manufacturer: 'Bayer',
      medicationForm: MedicationForm.TABLET,
      strength: '500mg',
      category: 'Antibiotic',
      drugClass: 'Fluoroquinolone',
      commonUses: 'Treatment of bacterial infections, UTIs',
      sideEffects: 'Nausea, diarrhea, dizziness, tendon problems',
      contraindications: 'Children under 18, pregnancy, tendon disorders',
      warnings: 'May cause tendon rupture. Avoid excessive sunlight',
      unitPrice: 1.80,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Pain Relief
    {
      id: 'med-012',
      name: 'Acetaminophen',
      genericName: 'Acetaminophen',
      brandName: 'Tylenol',
      manufacturer: 'Johnson & Johnson',
      medicationForm: MedicationForm.TABLET,
      strength: '500mg',
      category: 'Analgesic',
      drugClass: 'Non-opioid Analgesic',
      commonUses: 'Pain relief and fever reduction',
      sideEffects: 'Rare at therapeutic doses; liver damage with overdose',
      contraindications: 'Severe liver disease',
      warnings: 'Do not exceed 4000mg per day. Avoid alcohol',
      unitPrice: 0.15,
      isAvailable: true,
      requiresPrescription: false,
    },
    {
      id: 'med-013',
      name: 'Ibuprofen',
      genericName: 'Ibuprofen',
      brandName: 'Advil, Motrin',
      manufacturer: 'Pfizer',
      medicationForm: MedicationForm.TABLET,
      strength: '400mg',
      category: 'Analgesic',
      drugClass: 'NSAID',
      commonUses: 'Pain relief, fever reduction, inflammation',
      sideEffects: 'Stomach upset, heartburn, increased bleeding risk',
      contraindications: 'Active GI bleeding, severe kidney disease, aspirin allergy',
      warnings: 'Take with food. May increase cardiovascular risk with long-term use',
      unitPrice: 0.20,
      isAvailable: true,
      requiresPrescription: false,
    },
    {
      id: 'med-014',
      name: 'Tramadol',
      genericName: 'Tramadol Hydrochloride',
      brandName: 'Ultram',
      manufacturer: 'Janssen',
      medicationForm: MedicationForm.TABLET,
      strength: '50mg',
      category: 'Analgesic',
      drugClass: 'Opioid Analgesic',
      commonUses: 'Moderate to severe pain relief',
      sideEffects: 'Dizziness, nausea, constipation, drowsiness',
      contraindications: 'Severe respiratory depression, acute intoxication',
      warnings: 'May be habit-forming. Risk of seizures. Avoid alcohol',
      unitPrice: 0.80,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Thyroid
    {
      id: 'med-015',
      name: 'Levothyroxine',
      genericName: 'Levothyroxine Sodium',
      brandName: 'Synthroid, Levoxyl',
      manufacturer: 'AbbVie',
      medicationForm: MedicationForm.TABLET,
      strength: '75mcg',
      category: 'Thyroid',
      drugClass: 'Thyroid Hormone',
      commonUses: 'Treatment of hypothyroidism',
      sideEffects: 'Weight loss, tremor, nervousness (if dose too high)',
      contraindications: 'Untreated adrenal insufficiency, thyrotoxicosis',
      warnings: 'Take on empty stomach. Monitor TSH levels regularly',
      unitPrice: 0.40,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Gastrointestinal
    {
      id: 'med-016',
      name: 'Omeprazole',
      genericName: 'Omeprazole',
      brandName: 'Prilosec',
      manufacturer: 'AstraZeneca',
      medicationForm: MedicationForm.CAPSULE,
      strength: '20mg',
      category: 'Gastrointestinal',
      drugClass: 'Proton Pump Inhibitor',
      commonUses: 'Treatment of GERD, ulcers, acid reflux',
      sideEffects: 'Headache, diarrhea, abdominal pain',
      contraindications: 'Hypersensitivity to omeprazole',
      warnings: 'Long-term use may increase fracture risk. Take before meals',
      unitPrice: 0.70,
      isAvailable: true,
      requiresPrescription: false,
    },
    {
      id: 'med-017',
      name: 'Ondansetron',
      genericName: 'Ondansetron Hydrochloride',
      brandName: 'Zofran',
      manufacturer: 'GlaxoSmithKline',
      medicationForm: MedicationForm.TABLET,
      strength: '4mg',
      category: 'Gastrointestinal',
      drugClass: 'Antiemetic',
      commonUses: 'Prevention of nausea and vomiting',
      sideEffects: 'Headache, constipation, dizziness',
      contraindications: 'Congenital long QT syndrome',
      warnings: 'May cause QT prolongation. Use caution in heart disease',
      unitPrice: 2.00,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Neurological
    {
      id: 'med-018',
      name: 'Sumatriptan',
      genericName: 'Sumatriptan Succinate',
      brandName: 'Imitrex',
      manufacturer: 'GlaxoSmithKline',
      medicationForm: MedicationForm.TABLET,
      strength: '50mg',
      category: 'Neurological',
      drugClass: 'Triptan',
      commonUses: 'Treatment of migraine headaches',
      sideEffects: 'Tingling, dizziness, drowsiness, chest tightness',
      contraindications: 'Coronary artery disease, uncontrolled hypertension',
      warnings: 'Not for prevention. Take at onset of migraine',
      unitPrice: 15.00,
      isAvailable: true,
      requiresPrescription: true,
    },
    {
      id: 'med-019',
      name: 'Gabapentin',
      genericName: 'Gabapentin',
      brandName: 'Neurontin',
      manufacturer: 'Pfizer',
      medicationForm: MedicationForm.CAPSULE,
      strength: '300mg',
      category: 'Neurological',
      drugClass: 'Anticonvulsant',
      commonUses: 'Treatment of neuropathic pain, seizures',
      sideEffects: 'Dizziness, drowsiness, fatigue, peripheral edema',
      contraindications: 'Hypersensitivity to gabapentin',
      warnings: 'Do not stop abruptly. May cause dizziness',
      unitPrice: 0.50,
      isAvailable: true,
      requiresPrescription: true,
    },

    // Dermatology
    {
      id: 'med-020',
      name: 'Hydrocortisone Cream',
      genericName: 'Hydrocortisone',
      brandName: 'Cortaid',
      manufacturer: 'Johnson & Johnson',
      medicationForm: MedicationForm.CREAM,
      strength: '1%',
      category: 'Dermatology',
      drugClass: 'Topical Corticosteroid',
      commonUses: 'Treatment of skin inflammation, itching, rash',
      sideEffects: 'Skin thinning, burning, irritation',
      contraindications: 'Viral skin infections, acne, rosacea',
      warnings: 'Do not use on face for extended periods. Use thin layer',
      unitPrice: 8.00,
      isAvailable: true,
      requiresPrescription: false,
    },
  ];

  for (const medicationData of medications) {
    await prisma.medication.upsert({
      where: { id: medicationData.id },
      update: {},
      create: medicationData,
    });
  }

  console.log(`✅ Seeded ${medications.length} medications`);
}
