import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedMedicineInventory() {
  console.log('🌱 Seeding Medicine Inventory...');

  const now = new Date();
  const sixMonthsAgo = new Date(now);
  sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
  const threeMonthsAgo = new Date(now);
  threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
  const oneYearFromNow = new Date(now);
  oneYearFromNow.setFullYear(oneYearFromNow.getFullYear() + 1);
  const twoYearsFromNow = new Date(now);
  twoYearsFromNow.setFullYear(twoYearsFromNow.getFullYear() + 2);

  const inventory = [
    {
      medicationId: 'med-001',
      batchNumber: 'LIS2024001',
      expiryDate: twoYearsFromNow,
      quantity: 500,
      reorderLevel: 100,
      unitCost: 0.40,
      sellingPrice: 0.50,
      supplierName: 'MedSupply Inc',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'A1',
      shelfNumber: '3',
    },
    {
      medicationId: 'med-002',
      batchNumber: 'ATO2023087',
      expiryDate: oneYearFromNow,
      quantity: 300,
      reorderLevel: 50,
      unitCost: 0.90,
      sellingPrice: 1.20,
      supplierName: 'Pfizer Direct',
      purchaseDate: sixMonthsAgo,
      rackNumber: 'A1',
      shelfNumber: '4',
    },
    {
      medicationId: 'med-003',
      batchNumber: 'MET2024015',
      expiryDate: twoYearsFromNow,
      quantity: 400,
      reorderLevel: 80,
      unitCost: 0.60,
      sellingPrice: 0.80,
      supplierName: 'Novartis Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'A2',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-004',
      batchNumber: 'ASP2024099',
      expiryDate: twoYearsFromNow,
      quantity: 1000,
      reorderLevel: 200,
      unitCost: 0.05,
      sellingPrice: 0.10,
      supplierName: 'Bayer Wholesale',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'A2',
      shelfNumber: '2',
    },
    {
      medicationId: 'med-005',
      batchNumber: 'MET2024021',
      expiryDate: twoYearsFromNow,
      quantity: 750,
      reorderLevel: 150,
      unitCost: 0.20,
      sellingPrice: 0.30,
      supplierName: 'Generic Pharma',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'B1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-006',
      batchNumber: 'INS2024034',
      expiryDate: oneYearFromNow,
      quantity: 50,
      reorderLevel: 10,
      unitCost: 20.00,
      sellingPrice: 25.00,
      supplierName: 'Sanofi Direct',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'C1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-007',
      batchNumber: 'ALB2024056',
      expiryDate: oneYearFromNow,
      quantity: 200,
      reorderLevel: 40,
      unitCost: 12.00,
      sellingPrice: 15.00,
      supplierName: 'GSK Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'D1',
      shelfNumber: '2',
    },
    {
      medicationId: 'med-008',
      batchNumber: 'MON2024011',
      expiryDate: twoYearsFromNow,
      quantity: 180,
      reorderLevel: 30,
      unitCost: 2.00,
      sellingPrice: 2.50,
      supplierName: 'Merck Distributors',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'D1',
      shelfNumber: '3',
    },
    {
      medicationId: 'med-009',
      batchNumber: 'AMO2024078',
      expiryDate: oneYearFromNow,
      quantity: 600,
      reorderLevel: 120,
      unitCost: 0.45,
      sellingPrice: 0.60,
      supplierName: 'GSK Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'B2',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-010',
      batchNumber: 'AZI2024023',
      expiryDate: oneYearFromNow,
      quantity: 150,
      reorderLevel: 30,
      unitCost: 3.00,
      sellingPrice: 3.50,
      supplierName: 'Pfizer Direct',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'B2',
      shelfNumber: '2',
    },
    {
      medicationId: 'med-011',
      batchNumber: 'CIP2024045',
      expiryDate: oneYearFromNow,
      quantity: 200,
      reorderLevel: 40,
      unitCost: 1.50,
      sellingPrice: 1.80,
      supplierName: 'Bayer Wholesale',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'B3',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-012',
      batchNumber: 'ACE2024092',
      expiryDate: twoYearsFromNow,
      quantity: 800,
      reorderLevel: 150,
      unitCost: 0.10,
      sellingPrice: 0.15,
      supplierName: 'Johnson & Johnson',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'E1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-013',
      batchNumber: 'IBU2024067',
      expiryDate: twoYearsFromNow,
      quantity: 900,
      reorderLevel: 180,
      unitCost: 0.15,
      sellingPrice: 0.20,
      supplierName: 'Generic Pharma',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'E1',
      shelfNumber: '2',
    },
    {
      medicationId: 'med-014',
      batchNumber: 'TRA2024031',
      expiryDate: oneYearFromNow,
      quantity: 250,
      reorderLevel: 50,
      unitCost: 0.65,
      sellingPrice: 0.80,
      supplierName: 'Janssen Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'E2',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-015',
      batchNumber: 'LEV2024088',
      expiryDate: twoYearsFromNow,
      quantity: 500,
      reorderLevel: 100,
      unitCost: 0.30,
      sellingPrice: 0.40,
      supplierName: 'AbbVie Direct',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'F1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-016',
      batchNumber: 'OME2024055',
      expiryDate: oneYearFromNow,
      quantity: 350,
      reorderLevel: 70,
      unitCost: 0.55,
      sellingPrice: 0.70,
      supplierName: 'AstraZeneca',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'G1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-017',
      batchNumber: 'OND2024012',
      expiryDate: oneYearFromNow,
      quantity: 100,
      reorderLevel: 20,
      unitCost: 1.70,
      sellingPrice: 2.00,
      supplierName: 'GSK Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'G2',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-018',
      batchNumber: 'SUM2024027',
      expiryDate: oneYearFromNow,
      quantity: 80,
      reorderLevel: 15,
      unitCost: 13.00,
      sellingPrice: 15.00,
      supplierName: 'GSK Supply',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'H1',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-019',
      batchNumber: 'GAB2024041',
      expiryDate: twoYearsFromNow,
      quantity: 300,
      reorderLevel: 60,
      unitCost: 0.40,
      sellingPrice: 0.50,
      supplierName: 'Generic Pharma',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'H2',
      shelfNumber: '1',
    },
    {
      medicationId: 'med-020',
      batchNumber: 'HYD2024073',
      expiryDate: oneYearFromNow,
      quantity: 150,
      reorderLevel: 30,
      unitCost: 6.50,
      sellingPrice: 8.00,
      supplierName: 'Johnson & Johnson',
      purchaseDate: threeMonthsAgo,
      rackNumber: 'I1',
      shelfNumber: '1',
    },
  ];

  for (const inventoryData of inventory) {
    await prisma.medicineInventory.create({
      data: inventoryData,
    });
  }

  console.log(`✅ Seeded ${inventory.length} medicine inventory records`);
}
